/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/glbs/desert_scene.glb --output ./app/components/gltf/DesertScene.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['tripo_node_b0407be8-9ffa-414c-9c23-04a3d45acf38']: THREE.Mesh
  }
  materials: {
    ['tripo_material_b0407be8-9ffa-414c-9c23-04a3d45acf38']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/desert_scene.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_b0407be8-9ffa-414c-9c23-04a3d45acf38'].geometry} material={materials['tripo_material_b0407be8-9ffa-414c-9c23-04a3d45acf38']} />
    </group>
  )
}

useGLTF.preload('/glbs/desert_scene.glb')
