/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/glbs/desert-scene.glb --output ./app/components/gltf/DesertScene.tsx 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["tripo_node_b0407be8-9ffa-414c-9c23-04a3d45acf38"]: THREE.Mesh;
    ["tripo_node_79982d0e-6967-4175-bf0c-95a72becb20f"]: THREE.Mesh;
    ["tripo_node_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0"]: THREE.Mesh;
    ["tripo_node_e453c93e-dc44-47f4-942b-fd94d0ea676d"]: THREE.Mesh;
    ["tripo_node_247820ed-6658-4496-a722-c2e59723606d"]: THREE.Mesh;
    ["tripo_node_8b3130de-3e05-4f72-a76c-e176f53e9dd4"]: THREE.Mesh;
    ["tripo_node_79887436-6872-47a7-8405-2931b62fa083"]: THREE.Mesh;
    ["tripo_node_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0001"]: THREE.Mesh;
    ["tripo_node_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0002"]: THREE.Mesh;
  };
  materials: {
    ["tripo_material_b0407be8-9ffa-414c-9c23-04a3d45acf38"]: THREE.MeshStandardMaterial;
    ["tripo_material_79982d0e-6967-4175-bf0c-95a72becb20f"]: THREE.MeshStandardMaterial;
    ["tripo_mat_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0"]: THREE.MeshStandardMaterial;
    ["tripo_mat_e453c93e-dc44-47f4-942b-fd94d0ea676d"]: THREE.MeshStandardMaterial;
    ["tripo_mat_247820ed-6658-4496-a722-c2e59723606d"]: THREE.MeshStandardMaterial;
    ["tripo_mat_8b3130de-3e05-4f72-a76c-e176f53e9dd4"]: THREE.MeshStandardMaterial;
    ["tripo_mat_79887436-6872-47a7-8405-2931b62fa083"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/glbs/desert-scene.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes["tripo_node_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0"].geometry
        }
        material={materials["tripo_mat_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0"]}
        position={[-1.228, 1.519, -0.087]}
        scale={0.268}
      />
      <mesh
        geometry={
          nodes["tripo_node_e453c93e-dc44-47f4-942b-fd94d0ea676d"].geometry
        }
        material={materials["tripo_mat_e453c93e-dc44-47f4-942b-fd94d0ea676d"]}
        position={[-0.484, 1.564, -0.869]}
        rotation={[0.102, -1.1, -0.002]}
        scale={0.923}
      />
      <mesh
        geometry={
          nodes["tripo_node_247820ed-6658-4496-a722-c2e59723606d"].geometry
        }
        material={materials["tripo_mat_247820ed-6658-4496-a722-c2e59723606d"]}
        position={[0.882, 1.552, -0.508]}
        rotation={[0.057, 0.138, 0.002]}
      />
      <mesh
        geometry={
          nodes["tripo_node_8b3130de-3e05-4f72-a76c-e176f53e9dd4"].geometry
        }
        material={materials["tripo_mat_8b3130de-3e05-4f72-a76c-e176f53e9dd4"]}
        position={[-0.682, 1.514, -0.248]}
        rotation={[0.012, -0.016, -0.104]}
        scale={0.791}
      />
      <mesh
        geometry={
          nodes["tripo_node_79887436-6872-47a7-8405-2931b62fa083"].geometry
        }
        material={materials["tripo_mat_79887436-6872-47a7-8405-2931b62fa083"]}
        position={[0.681, 1.414, -0.016]}
        rotation={[0.001, -0.695, -0.071]}
        scale={0.325}
      />
      <mesh
        geometry={
          nodes["tripo_node_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0001"].geometry
        }
        material={materials["tripo_mat_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0"]}
        position={[0.538, 1.455, -0.915]}
        scale={0.268}
      />
      <mesh
        geometry={
          nodes["tripo_node_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0002"].geometry
        }
        material={materials["tripo_mat_d7a7b6b2-9906-4d91-a7d6-0428d1ebd3f0"]}
        position={[0.499, 1.374, -0.175]}
        scale={0.126}
      />
      <mesh
        geometry={
          nodes["tripo_node_b0407be8-9ffa-414c-9c23-04a3d45acf38"].geometry
        }
        material={
          materials["tripo_material_b0407be8-9ffa-414c-9c23-04a3d45acf38"]
        }
        position={[-0.026, 1.638, -0.229]}
        rotation={[0, -1.571, 0]}
        scale={2.941}
      />
      <mesh
        geometry={
          nodes["tripo_node_79982d0e-6967-4175-bf0c-95a72becb20f"].geometry
        }
        material={
          materials["tripo_material_79982d0e-6967-4175-bf0c-95a72becb20f"]
        }
        position={[0.972, 1.414, -0.755]}
        scale={0.447}
      />
    </group>
  );
}

useGLTF.preload("/glbs/desert-scene.glb");
