export const MOCK_RANKING_DATA = [
  {
    ranking: 1,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 10,
    cactus_germination: "10/10/2023",
    score: 5000,
    improved: true,
  },
  {
    ranking: 2,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 5,
    cactus_germination: "05/05/2022",
    score: 3000,
    improved: false,
  },
  {
    ranking: 3,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 8,
    cactus_germination: "08/08/2021",
    score: 4000,
    improved: true,
  },
  {
    ranking: 4,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 12,
    cactus_germination: "12/12/2020",
    score: 6000,
    improved: false,
  },
  {
    ranking: 5,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 6,
    cactus_germination: "06/06/2022",
    score: 3500,
    improved: true,
  },
  {
    ranking: 6,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 9,
    cactus_germination: "09/09/2021",
    score: 4500,
    improved: false,
  },
  {
    ranking: 7,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 11,
    cactus_germination: "11/11/2020",
    score: 5500,
    improved: true,
  },
  {
    ranking: 8,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 7,
    cactus_germination: "07/07/2022",
    score: 3250,
    improved: false,
  },
  {
    ranking: 9,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 10,
    cactus_germination: "10/10/2021",
    score: 4250,
    improved: true,
  },
  {
    ranking: 10,
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    cactus_age: 8,
    cactus_germination: "08/08/2022",
    score: 5250,
    improved: false,
  },
];
