export const MOCK_DATA = [
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5000,
    mentions: 1,
    engagement: 8,
    relevance: 7,
    depth: 1,
    novelty: 4,
    sentiment: 2,
    level: 45.3,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3000,
    mentions: 6,
    engagement: 3,
    relevance: 2,
    depth: 2,
    novelty: 0,
    sentiment: 7,
    level: 72.6,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4000,
    mentions: 7,
    engagement: 3,
    relevance: 9,
    depth: 8,
    novelty: 4,
    sentiment: 6,
    level: 33.7,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 6000,
    mentions: 8,
    engagement: 1,
    relevance: 5,
    depth: 6,
    novelty: 5,
    sentiment: 6,
    level: 87.1,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3500,
    mentions: 7,
    engagement: 7,
    relevance: 5,
    depth: 3,
    novelty: 7,
    sentiment: 9,
    level: 64.9,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4500,
    mentions: 9,
    engagement: 6,
    relevance: 5,
    depth: 3,
    novelty: 8,
    sentiment: 7,
    level: 12.4,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5500,
    mentions: 0,
    engagement: 5,
    relevance: 7,
    depth: 7,
    novelty: 2,
    sentiment: 7,
    level: 56.3,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3250,
    mentions: 7,
    engagement: 5,
    relevance: 4,
    depth: 9,
    novelty: 3,
    sentiment: 6,
    level: 91.8,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4250,
    mentions: 4,
    engagement: 0,
    relevance: 7,
    depth: 6,
    novelty: 2,
    sentiment: 6,
    level: 48.2,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5250,
    mentions: 1,
    engagement: 4,
    relevance: 7,
    depth: 9,
    novelty: 6,
    sentiment: 9,
    level: 77.3,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5000,
    mentions: 1,
    engagement: 8,
    relevance: 7,
    depth: 1,
    novelty: 4,
    sentiment: 2,
    level: 45.3,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3000,
    mentions: 6,
    engagement: 3,
    relevance: 2,
    depth: 2,
    novelty: 0,
    sentiment: 7,
    level: 72.6,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4000,
    mentions: 7,
    engagement: 3,
    relevance: 9,
    depth: 8,
    novelty: 4,
    sentiment: 6,
    level: 33.7,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 6000,
    mentions: 8,
    engagement: 1,
    relevance: 5,
    depth: 6,
    novelty: 5,
    sentiment: 6,
    level: 87.1,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3500,
    mentions: 7,
    engagement: 7,
    relevance: 5,
    depth: 3,
    novelty: 7,
    sentiment: 9,
    level: 64.9,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4500,
    mentions: 9,
    engagement: 6,
    relevance: 5,
    depth: 3,
    novelty: 8,
    sentiment: 7,
    level: 12.4,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5500,
    mentions: 0,
    engagement: 5,
    relevance: 7,
    depth: 7,
    novelty: 2,
    sentiment: 7,
    level: 56.3,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3250,
    mentions: 7,
    engagement: 5,
    relevance: 4,
    depth: 9,
    novelty: 3,
    sentiment: 6,
    level: 91.8,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4250,
    mentions: 4,
    engagement: 0,
    relevance: 7,
    depth: 6,
    novelty: 2,
    sentiment: 6,
    level: 48.2,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5250,
    mentions: 1,
    engagement: 4,
    relevance: 7,
    depth: 9,
    novelty: 6,
    sentiment: 9,
    level: 77.3,
  },
];

export const BLOCK_USER_NAMES = ["Froggy", "pffffffnsd", "TheGardenerTeam"];
