export const MOCK_DATA = [
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5000,
    mentions: 13,
    engagement: 82,
    relevance: 7,
    depth: 11,
    novelty: 41,
    sentiment: 28,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3000,
    mentions: 60,
    engagement: 38,
    relevance: 2,
    depth: 2,
    novelty: 4,
    sentiment: 72,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4000,
    mentions: 78,
    engagement: 33,
    relevance: 98,
    depth: 83,
    novelty: 43,
    sentiment: 64,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 6000,
    mentions: 83,
    engagement: 12,
    relevance: 5,
    depth: 64,
    novelty: 52,
    sentiment: 67,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3500,
    mentions: 75,
    engagement: 74,
    relevance: 59,
    depth: 39,
    novelty: 78,
    sentiment: 90,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4500,
    mentions: 91,
    engagement: 67,
    relevance: 5,
    depth: 36,
    novelty: 85,
    sentiment: 73,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5500,
    mentions: 3,
    engagement: 57,
    relevance: 74,
    depth: 76,
    novelty: 21,
    sentiment: 72,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3250,
    mentions: 76,
    engagement: 52,
    relevance: 4,
    depth: 92,
    novelty: 39,
    sentiment: 69,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4250,
    mentions: 47,
    engagement: 3,
    relevance: 75,
    depth: 65,
    novelty: 23,
    sentiment: 60,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5250,
    mentions: 11,
    engagement: 46,
    relevance: 79,
    depth: 95,
    novelty: 64,
    sentiment: 97,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5000,
    mentions: 13,
    engagement: 82,
    relevance: 7,
    depth: 11,
    novelty: 41,
    sentiment: 28,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3000,
    mentions: 60,
    engagement: 38,
    relevance: 2,
    depth: 2,
    novelty: 4,
    sentiment: 72,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4000,
    mentions: 78,
    engagement: 33,
    relevance: 98,
    depth: 83,
    novelty: 43,
    sentiment: 64,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 6000,
    mentions: 83,
    engagement: 12,
    relevance: 5,
    depth: 64,
    novelty: 52,
    sentiment: 67,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3500,
    mentions: 75,
    engagement: 74,
    relevance: 59,
    depth: 39,
    novelty: 78,
    sentiment: 90,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4500,
    mentions: 91,
    engagement: 67,
    relevance: 5,
    depth: 36,
    novelty: 85,
    sentiment: 73,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5500,
    mentions: 3,
    engagement: 57,
    relevance: 74,
    depth: 76,
    novelty: 21,
    sentiment: 72,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 3250,
    mentions: 76,
    engagement: 52,
    relevance: 4,
    depth: 92,
    novelty: 39,
    sentiment: 69,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 4250,
    mentions: 47,
    engagement: 3,
    relevance: 75,
    depth: 65,
    novelty: 23,
    sentiment: 60,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5250,
    mentions: 11,
    engagement: 46,
    relevance: 79,
    depth: 95,
    novelty: 64,
    sentiment: 97,
  },
  {
    avatar: "/images/sami_profile_photo.png",
    twitter_handler: "OnlyOneSami",
    twitter_link: "https://x.com/OnlyOneSami",
    score: 5250,
    mentions: 11,
    engagement: 46,
    relevance: 79,
    depth: 95,
    novelty: 64,
    sentiment: 97,
  },
];
